export const Branches = [
    'Fiat',
    'Renault',
    'Peugeot',
    'Honda',
    'Jeep',
    'Chevrolet',
    'Nissan',
    'Hyundai',
    'Citroen',
    'Ford',
    'Wolkswagen',
    'Mitsubishi',
    'Toyota',
    'BMW',
    'Volvo',
    'Mini Cooper',
    'Mercedes-Benz',
    'Audi',
    'KIA',
    'Land Rover',
    'Porsche',
    'Dodge',
    'RAM',
    'Jaguar',
    
]